// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmNB1bmDeiAKm_7IhpVB_jDSwtZG3pQzs',
    appId: '1:145450046365:web:51ff034f39b3ca30cf5574',
    messagingSenderId: '145450046365',
    projectId: 'chat-app-c52c1',
    authDomain: 'chat-app-c52c1.firebaseapp.com',
    storageBucket: 'chat-app-c52c1.appspot.com',
    measurementId: 'G-S3LEP20HDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9Ts2JAAFxAHjFv8s08v2kvf3tfIjb_k',
    appId: '1:145450046365:android:bfa00d82528948aacf5574',
    messagingSenderId: '145450046365',
    projectId: 'chat-app-c52c1',
    storageBucket: 'chat-app-c52c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2IrOvwo61iluHUl_MqcksD6u6Av4ZZM',
    appId: '1:145450046365:ios:66c088b41e6691bfcf5574',
    messagingSenderId: '145450046365',
    projectId: 'chat-app-c52c1',
    storageBucket: 'chat-app-c52c1.appspot.com',
    iosClientId: '145450046365-dqd1kgcafkd1faehklokc192hunfs88p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv2IrOvwo61iluHUl_MqcksD6u6Av4ZZM',
    appId: '1:145450046365:ios:66c088b41e6691bfcf5574',
    messagingSenderId: '145450046365',
    projectId: 'chat-app-c52c1',
    storageBucket: 'chat-app-c52c1.appspot.com',
    iosClientId: '145450046365-dqd1kgcafkd1faehklokc192hunfs88p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
